posco:
    name: 3ê¸°4444dev
    count: 20
    datasource:
        url: jdbc:mysql://localhost:3306/insta?serverTimezone=UTC&characterEncoding=UTF-8
        username: root
        password: 1234
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/insta?serverTimezone=UTC&characterEncoding=UTF-8
        username: root
        password: '{cipher}da48a70f34e73581993e271b9ee39a5a0d877c228d06bca69b90bf92dc688046'
jwt:
    secret_key: SECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEY
    expTime: 86400000